### ISSUE TITLE
allowed categories removal broke the categories option

### ISSUE THREAD

**Issue by pbearne** [rinatkhaziev/wp-frontend-uploader#64]
the fix is

LN 301 
'post_category' => isset( $_POST['post_category'] ) ? array( (int) $_POST['post_category'] ): 0,
As wp_insert_post() expects an array
https://codex.wordpress.org/Function_Reference/wp_insert_post

**Comment by HP1996** [comment]
@pbearne 
Any thoughts on using the checkboxes, radio buttons, or dropdown to select different category ids?
Because, I can't seem to make that work..

**Comment by HP1996** [comment]
How I picture this woking is something like:

[fu-upload-form suppress_default_fields=true class=user-gallery title='Upload Your Portfolio Images' form_layout=post_media post_type=gallery append_to_post=true] [input type=text name=post_title id=title class=required description='Your First Name'] **[category=select name=foo class=select id=ug_select description='Pick A Profession' values=24:Painter,25:Photograpger]** [input type=file name=upload id=ug_photo class=required description='Select Your Images' multiple=multiple] [input type=submit class=btn value='Upload'] [/fu-upload-form]

^^^where 25 & 24 are the category ids of the gallery post_type.

**Comment by HP1996** [comment]
@rinatkhaziev 

...Or perhaps this could be achieved with nesting shortcodes?
[category]
[select name=foo class=select id=ug_select description='Pick A Profession' values=24:Painter,25:Photograpger]
[/category]
