### ISSUE TITLE
Placeholder Element feature

### ISSUE THREAD

**Issue by janmei** [rinatkhaziev/wp-frontend-uploader#79]
Hey Guys, 

is it possible to implement a placeholder attribute to the shortcodes?
Something like the description attribute but for placeholder. 

`[input ... placeholder=""]`

With this included this plugin is pretty damn nice.

Thanks in advance.
Cheers.

**Comment by rinatkhaziev** [comment]
Added in 1.3 (you can download from wp.org or from here)
