### ISSUE TITLE
This post type is not allowed.

### ISSUE THREAD

**Issue by dan-online** [rinatkhaziev/wp-frontend-uploader#88]
When using the example shortcode:
```
[fu-upload-form form_layout="post_media" title="Upload your story and image"
class="my-class validate" post_type="story" append_to_post="true"
success_page="http://example.com/success-page/" category="1" ][/fu-upload-form]
```

I get 

```
There was an error with your submission

This post type is not allowed.
```

**Comment by rinatkhaziev** [comment]
It's a setting you can adjust in the plugin's settings page.

**Comment by dan-online** [comment]
![image](https://user-images.githubusercontent.com/41877062/77573128-7990b100-6ed0-11ea-981c-bcb2d5aa2ac1.png)

Is it these options?

**Comment by rinatkhaziev** [comment]
Yes, it's only listing the public ones. Is `story` a private post type?

**Comment by dan-online** [comment]
Oh ok I understand now, so when I change that to "post", it leads me to https://thebasilisk.org/wp-admin/admin-ajax.php and the error of There has been a critical error on your website. Learn more about debugging in WordPress.

Thanks for your help so far by the way, I'm quite new to Wordpress as I never use it

**Comment by rinatkhaziev** [comment]
No problem! 

Current versions of WP send you an email with the error and its stack trace. Or you can check your server logs to see what is the error.

**Comment by dan-online** [comment]
Oh ok, I'll take a look! Might I leave this open until I figure out the issue or if I run into any more problems?

**Comment by dan-online** [comment]
Ok so there were no errors sent by email but I'm sure its a pretty new version of WP, any other ideas on what it could be?
